# Generated by Django 3.1.6 on 2021-03-29 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qtec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('searched_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
