# Generated by Django 3.1.6 on 2021-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI1', models.CharField(max_length=100)),
                ('IMEI2', models.CharField(max_length=100)),
                ('MAC_ID', models.CharField(max_length=100)),
                ('Status', models.IntegerField()),
                ('Competitor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
